stages:
  - build

python:
  tags:
    - linux
  stage: build
  image: python:3.8.11
  before_script:
    - apt update -y
    - apt install -y libsasl2-dev libldap2-dev libssl-dev
    - pip install --upgrade pip
    - pip install -r requirements.txt
  script:
    - cd ${CI_PROJECT_DIR}
    - python --version
    - ./dbtool.py --version
    - cd reporter
    - make

node:
  tags:
    - linux
  stage: build
  image: node
  before_script:
    - apt update -y
    - cd ${CI_PROJECT_DIR}/frontend
    - npm install
  script:
    - npm run build
