stages:
  - build

python-3.10.14:
  tags:
    - linux
  stage: build
  image: python:3.10.14
  before_script:
    - apt update -y
    - apt install -y libsasl2-dev libldap2-dev libssl-dev
    - pip install --upgrade pip
  script:
    - cd ${CI_PROJECT_DIR}
    - pip install -r requirements.txt
    - python --version
    - ./dbtool.py --version
    - cd reporter
    - make

python-3.11.9:
  tags:
    - linux
  stage: build
  image: python:3.11.9
  before_script:
    - apt update -y
    - apt install -y libsasl2-dev libldap2-dev libssl-dev
    - pip install --upgrade pip
  script:
    - cd ${CI_PROJECT_DIR}
    - pip install -r requirements.txt
    - python --version
    - ./dbtool.py --version
    - cd reporter
    - make

node:
  tags:
    - linux
  stage: build
  image: node
  before_script:
    - apt update -y
    - cd ${CI_PROJECT_DIR}/frontend
    - npm install
  script:
    - npm run build
