import * as React from "react";

import Box from "@mui/material/Box";

import List from "@mui/material/List";
import ListItem from "@mui/material/ListItem";
import ListItemAvatar from "@mui/material/ListItemAvatar";
import ListItemText from "@mui/material/ListItemText";
import Avatar from "@mui/material/Avatar";

function refreshMessages(seed = 1) {
  const getRandomInt = (max, seed) =>
    Math.floor((Math.random() % seed) * Math.floor(max));

  return Array.from(new Array(20)).map(
    () => messageExamples[getRandomInt(messageExamples.length, seed)]
  );
}

export function RandomList(props) {
  const [messages, setMessages] = React.useState(() =>
    refreshMessages(props.seed || 1)
  );

  return (
    <div className="fullHeight paper scrollable container">
      <Box sx={{ pt: 6, pb: 10 }}>
        <List>
          {messages.map(({ primary, secondary, person }, index) => (
            <ListItem key={index}>
              <ListItemAvatar>
                <Avatar alt="Picture" src={person} />
              </ListItemAvatar>
              <ListItemText
                primary={primary}
                primaryTypographyProps={{ color: "var(--system-foreground)" }}
                secondary={secondary}
                secondaryTypographyProps={{ color: "var(--gray)" }}
              />
            </ListItem>
          ))}
        </List>
      </Box>
    </div>
  );
}

const messageExamples = [
  {
    primary: "Brunch this week?",
    secondary:
      "I'll be in the neighbourhood this week. Let's grab a bite to eat",
    person: "/static/images/icon64.png",
  },
  {
    primary: "Birthday Gift",
    secondary: `Do you have a suggestion for a good present for John on his work
        anniversary. I am really confused & would love your thoughts on it.`,
    person: "/static/images/icon64.png",
  },
  {
    primary: "Recipe to try",
    secondary:
      "I am try out this new BBQ recipe, I think this might be amazing",
    person: "/static/images/icon64.png",
  },
  {
    primary: "Yes!",
    secondary: "I have the tickets to the ReactConf for this year.",
    person: "/static/images/icon64.png",
  },
  {
    primary: "Doctor's Appointment",
    secondary:
      "My appointment for the doctor was rescheduled for next Saturday.",
    person: "/static/images/icon64.png",
  },
  {
    primary: "Discussion",
    secondary: `Menus that are generated by the bottom app bar (such as a bottom
        navigation drawer or overflow menu) open as bottom sheets at a higher elevation
        than the bar.`,
    person: "/static/images/icon64.png",
  },
  {
    primary: "Summer BBQ",
    secondary: `Who wants to have a cookout this weekend? I just got some furniture
        for my backyard and would love to fire up the grill.`,
    person: "/static/images/icon64.png",
  },
];
